### ISSUE TITLE
Mac?

### ISSUE THREAD

**Issue by Choccy-vr** [fifonik/ElegooNeptuneThumbnailPrusaMod#9]
Is it possible to add mac support

**Comment by Bart1909** [comment]
Have a look at this part: https://github.com/fifonik/ElegooNeptuneThumbnailPrusaMod?tab=readme-ov-file#running-from-the-python-script

You simply have to install Python and PyQT6 on your mac and can invoke the script then.

In addition, you could also build the binary as described here: https://github.com/fifonik/ElegooNeptuneThumbnailPrusaMod?tab=readme-ov-file#building-your-own-executable-from-the-python-script
